apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: estate-ci
resources:
  - namespace.yaml
  - service-account.yaml
  - config-map.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - services.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: estate-ci
    includeSelectors: true
    includeTemplates: true
