apiVersion: v1
kind: ServiceAccount
metadata:
  name: estate-ci-api
  annotations:
    estate-ci.mindclade.dev/connection: unresolved-workload-identity
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: estate-ci-web
automountServiceAccountToken: false
